### ISSUE TITLE
Cannot read property of createResizedImage of undefined :(

### ISSUE THREAD

**Issue by ORESoftware** [bamlab/react-native-image-resizer#234]
There is no "main" property in package.json:

```json
{
  "name": "react-native-image-resizer",
  "version": "1.2.1",
  "description": "Rescale local images with React Native",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/bamlab/react-native-image-resizer.git"
  },
  "keywords": [
    "react-native",
    "react",
    "android",
    "ios",
    "images",
    "image",
    "image-resizer",
    "scaling",
    "scale",
    "resize"
  ],
  "peerDependencies": {
    "react": "^15.4.0 || ^16.0.0-alpha",
    "react-native": ">=v0.40.0"
  },
  "author": "Florian Rival <florianr@bam.tech> (http://bam.tech)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/bamlab/react-native-image-resizer/issues"
  },
  "homepage": "https://github.com/bamlab/react-native-image-resizer#readme",
  "devDependencies": {
    "cz-conventional-changelog": "^1.2.0"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  }
}
```

and I am getting:

<img width="376" alt="Screen Shot 2020-05-06 at 2 21 35 PM" src="https://user-images.githubusercontent.com/11139560/81229585-ebb2e600-8fa4-11ea-84d7-29282ebe72e3.png">

and the code is just:

```typescript
import ImageResizer from 'react-native-image-resizer';

 ImageResizer.createResizedImage(
            imageUri,
            newWidth,
            newHeight,
            'JPEG',
            1
        ).then((response) => {
            console.log('successfully resized image:', response);
            return getLocalImageBase64(response.uri);
        });
```

everything compiles with typescript tho! :(

there is no **index.js** file in the project:

<img width="345" alt="Screen Shot 2020-05-06 at 2 22 45 PM" src="https://user-images.githubusercontent.com/11139560/81229699-1a30c100-8fa5-11ea-8bd4-662970bbbc2b.png">

**Comment by superbelko1** [comment]
oh same problem trying to resolve(

**Comment by ORESoftware** [comment]
I think it's b/c the project is missing an index.js file

**Comment by PierreCapo** [comment]
@ORESoftware @superbelko1 I have just published a new version (1.2.2) with an index.js file and a main key in the package.json. Can you try it out and tell me if that fixes your problem ? ty

**Comment by ORESoftware** [comment]
Yeah I don't think it worked, I logged "RAAZZZOOOOM":

<img width="887" alt="Screen Shot 2020-05-07 at 12 19 00 PM" src="https://user-images.githubusercontent.com/11139560/81335838-195b6600-905d-11ea-99ac-417426bcf655.png">

and I still get that error:

<img width="425" alt="Screen Shot 2020-05-07 at 12 20 37 PM" src="https://user-images.githubusercontent.com/11139560/81335896-33954400-905d-11ea-99c8-04625d660e41.png">

I am not sure why :(

**Comment by ORESoftware** [comment]
ok so it's not because of index.js, it's because NativeModules from react-native doesn't have the export...

if we run:

```
import { NativeModules, Platform } from 'react-native';
 console.log(Object.keys(NativeModules));
```

I get:

```
  "AppState",
  "DevSettings",
  "DevLoadingView",
  "StatusBarManager",
  "LinkingManager",
  "ExponentNotifications",
  "ExponentUpdates",
  "ExceptionsManager",
  "NativeUnimoduleProxy",
  "UMReactNativeEventEmitter",
  "AsyncLocalStorage",
  "AIRGoogleMapManager",
  "AIRGoogleMapMarkerManager",
  "AIRMapManager",
  "AIRMapMarkerManager",
  "LottieAnimationView",
  "ExponentAR",
  "ExpoNativeModuleIntrospection",
  "ExponentSplashScreen",
  "ExponentTest",
  "RNCViewPager",
  "ReanimatedModule",
  "RNAWSCognito",
  "RNCAppearance",
  "RNCNetInfo",
  "RNCSafeAreaView",
  "RNCWebViewManager",
  "RNGestureHandlerModule",
  "RNSharedElementTransition",
  "RNSVGRenderableManager",
  "RNSVGCircleManager",
  "RNSVGEllipseManager",
  "RNSVGGroupManager",
  "RNSVGForeignObjectManager",
  "RNSVGImageManager",
  "RNSVGLineManager",
  "RNSVGMarkerManager",
  "RNSVGMaskManager",
  "RNSVGPathManager",
  "RNSVGPatternManager",
  "RNSVGRectManager",
  "RNSVGSvgViewManager",
  "RNSVGTextManager",
  "RNSVGTextPathManager",
  "RNSVGTSpanManager",
  "RNSVGUseManager",
  "RNViewShot",
  "AccessibilityManager",
  "AlertManager",
  "Clipboard",
  "DeviceInfo",
  "I18nManager",
  "KeyboardObserver",
  "ModalManager",
  "RedBox",
  "ScrollViewManager",
  "SourceCode",
  "Timing",
  "TVNavigationEventEmitter",
  "UIManager",
  "WebSocketModule",
  "ImageEditingManager",
  "ImageStoreManager",
  "PlatformConstants",
  "ActionSheetManager",
  "NativeAnimatedModule",
  "BlobModule",
  "FileReaderModule",
  "ImageViewManager",
  "NetInfo",
  "Networking",
  "SettingsManager",
  "Vibration",
```

**Comment by ORESoftware** [comment]
So perhaps the module is not linked properly. I am in an expo project and the install instructions say:

```
yarn add react-native-image-resizer
cd ios && pod install
```

but I don't have a folder called "ios" in my project

**Comment by PierreCapo** [comment]
I'm not sure they have added a way to add custom native modules on expo. You need to use what they provide or eject.

**Comment by vincentzierigen** [comment]
I'm still getting this issue on 1.2.2, I use react-cli, not expo
